USE [master]
GO

/****** Object:  Database [DemoDB]    Script Date: 12/31/2019 5:01:47 PM ******/
CREATE DATABASE [DemoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoDB', FILENAME = N'[Path]\Data\DemoDB.mdf' , SIZE = 10485760KB , MAXSIZE = 20971520KB , FILEGROWTH = 131072KB )
 LOG ON 
( NAME = N'DemoDB_log', FILENAME = N'[Path]\DemoDB_log.ldf' , SIZE = 102400KB , MAXSIZE = 2097152KB , FILEGROWTH = 10240KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DemoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DemoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoDB] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [DemoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DemoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DemoDB] SET  MULTI_USER 
GO

ALTER DATABASE [DemoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DemoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DemoDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DemoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DemoDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DemoDB] SET  READ_WRITE 
GO


